export const ROLES = {
  SUPER_SUPER_ADMIN: "super_super_admin", // App owner
  SUPER_ADMIN: "super_admin", // School super admin
  SCHOOL_ADMIN: "school_admin", // School admin (principal)
  TEACHER: "teacher", // Regular teacher
  CLASS_TEACHER: "class_teacher", // Teacher with class oversight
  BURSAR: "bursar", // Fee management
  STUDENT: "student", // Student
  PARENT: "parent", // Parent
}

export const PERMISSIONS = {
  CREATE_SCHOOL: "create_school",
  MANAGE_SCHOOL: "manage_school",
  MANAGE_USERS: "manage_users",
  MANAGE_CLASSES: "manage_classes",
  MANAGE_SUBJECTS: "manage_subjects",
  MANAGE_STUDENTS: "manage_students",
  MANAGE_FEES: "manage_fees",
  MANAGE_RESULTS: "manage_results",
  VIEW_RESULTS: "view_results",
  TOGGLE_STUDENT_REGISTRATION: "toggle_student_registration",
}

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_SUPER_ADMIN]: [PERMISSIONS.CREATE_SCHOOL, PERMISSIONS.MANAGE_SCHOOL, PERMISSIONS.MANAGE_USERS],
  [ROLES.SUPER_ADMIN]: [PERMISSIONS.CREATE_SCHOOL, PERMISSIONS.MANAGE_SCHOOL, PERMISSIONS.MANAGE_USERS],
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.MANAGE_SCHOOL,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.MANAGE_SUBJECTS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.MANAGE_RESULTS,
  ],
  [ROLES.TEACHER]: [PERMISSIONS.MANAGE_RESULTS, PERMISSIONS.TOGGLE_STUDENT_REGISTRATION],
  [ROLES.CLASS_TEACHER]: [
    PERMISSIONS.MANAGE_RESULTS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.TOGGLE_STUDENT_REGISTRATION,
  ],
  [ROLES.BURSAR]: [PERMISSIONS.MANAGE_FEES],
  [ROLES.STUDENT]: [PERMISSIONS.VIEW_RESULTS],
  [ROLES.PARENT]: [PERMISSIONS.VIEW_RESULTS],
}
